Fix production color label
cashapp/backfila pull request #239
Opened 2022-03-10 20:33 UTC by wildeyedskies

Move away from chick-fil-a branding. Add a happy creature

2022-03-10 20:55 UTC, shellderp commented
why is this being changed? the graphics were great

2022-03-10 20:58 UTC, keeferrourke approved these changes
Love the happy creature :)

2022-03-10 20:59 UTC, shellderp requested changes
Please make it configurable if you really want this, or I'll have to fork the repo

2022-03-10 21:02 UTC, keeferrourke commented
> why is this being changed? the graphics were great

The graphics may have been great, but so are the new ones! Association with Chick-fil-a is not really desirable, considering the brand's exclusionary and [anti-LGBT history](https://en.wikipedia.org/wiki/Chick-fil-A_and_LGBT_people).

2022-03-11 18:29 UTC, mpawliszyn commented on README.md
> +Note: some instructions here are out of date
Which instructions? It is quite possible.

2022-03-11 18:58 UTC, escardin approved these changes

2022-03-11 19:24 UTC, shellderp commented
thanks, can you make the favicon a 🅱️ ? then it's distinguishable from other cash sites. Would be good to run local dev and make sure it renders ok

2022-03-11 20:08 UTC, wildeyedskies commented
> thanks, can you make the favicon a 🅱️ ? then it's distinguishable from other cash sites. Would be good to run local dev and make sure it renders ok

Yes, done now!

2022-03-11 20:41 UTC, shellderp commented
I think you missed one favicon? There's two 🤔

2022-03-11 20:54 UTC, wildeyedskies commented
> I think you missed one favicon? There's two 🤔

Gotcha, I changed out the second one

2022-03-11 20:58 UTC, shellderp approved these changes

2022-03-11 21:22 UTC, merged